/online_calibration:
  ros__parameters:
    "log_path": "/DATA/log_files"
    "eval_log_dir": "/DATA/eval_log_files"
    "relative intensity threshold": 0.7
    "DBSCAN epsilon": 0.7
    "DBSCAN min samples": 20
    "maximum neighbor distance": 0.6
    "minimum velocity": 0.05
    "window size": 8
    "max. vector angle [deg]": 80.0
    "sample_rate_Hz": 9.8
    "outlier_mean_factor": 3.0
    "max_point_number_change_ratio": 0.8
    "normal_cosine_weight": 0
    "point_number_weight": 0
    "gaussian_range_weight": 0
    "minimum_iterations_until_convergence": 400
    "disable_outlier_rejection": True
    "sigma_min_w_threshold": 0.0001  # threshold for smallest singular value of whitened Jacobian
    "condition_number_threshold": 1000.0  # OPTIONAL: condition number threshold for convergence
    "rot_std_threshold_deg": 0.3  # OPTIONAL: max 0.5 degree per axis
    "trans_std_threshold_m": 0.01  # OPTIONAL: max 2 cm per axis
