/online_calibration:
  ros__parameters:
    "log_path": "/DATA/log_files"
    "eval_log_dir": "/DATA/eval_log_files"
    "relative intensity threshold": 0.7
    "DBSCAN epsilon": 0.4
    "DBSCAN min samples": 9
    "maximum neighbor distance": 0.4
    "minimum velocity": 0.05
    "window size": 12
    "max. vector angle [deg]": 80.0
    "sample_rate_Hz": 10.0
    "outlier_mean_factor": 3.0
    "max_point_number_change_ratio": 0.8
    "normal_cosine_weight": 0
    "point_number_weight": 0
    "gaussian_range_weight": 0
    "use_covariance_trace_weight": False
    "shape_similarity_weight": 0.0
    "shape_similarity_k_factor": 10.0
    "disable_outlier_rejection": True
    "minimum_iterations_until_convergence": 400
    "sensor_sigma_range_m": 0.05
    "sensor_sigma_azimuth_deg": 0.2 
    "sensor_sigma_elevation_deg": 0.2
    # ICP refinement
    "enable_icp_refinement": True
    "icp_inlier_threshold": 0.02
    "icp_max_iterations": 100
    "icp_update_transformation": True
    "calibration_subsample_step": 1  # use every n-th calibration pair (1 = use all)
